const products = [
  {
    title: "Magnetite",
    category: 'Reggae',
    price: 89.0,
    img: "../../assets/img/1.jpg",
    band: "Scalene",
    year: 2017,
    id: 0,
  },
  {
    title: "Acabou o Chorare",
    category: 'MPB',
    price: 66.0,
    img: "../../assets/img/2.jpg",
    band: "Novos Baianos",
    year: 1972,
    id: 1,
  },
  {
    title: "Nirvana Discografia",
    category: 'Rock',
    price: 50.0,
    img: "../../assets/img/3.jpg",
    band: "Nirvava",
    year: 1990,
    id: 2,
  },
  {
    title: "Both Sides",
    category: 'Rap',
    price: 22.0,
    img: "../../assets/img/4.jpg",
    band: "Phil Collins",
    year: 1993,
    id: 3,
  },
  {
    title: "November Rain",
    category: 'Rock',
    price: 46.0,
    img: "../../assets/img/2.jpg",
    band: "Guns N' Roses",
    year: 1992,
    id: 4,
  },
  {
    title: "Preciso me Encontrar",
    category: 'Samba',
    price: 57.0,
    img: "../../assets/img/3.jpg",
    band: "Cartola",
    year: 1976,
    id: 5,
  },
  {
    title: "Renegades",
    category: 'Rap',
    price: 32.0,
    img: "../../assets/img/4.jpg",
    band: "Yelawolf",
    year: 2019,
    id: 6,
  },
];

// const categories = [
//   "Todos",
//   "Pop",
//   "MPB",
//   "Forró",
//   "Samba",
//   "Baião",
//   "Rap",
//   "Hip-Hop",
//   "Rock",
//   "Reggae",
//   "Country",
//   "Gospel",
// ];
